### ISSUE TITLE
list() won't match zero length lists

### ISSUE THREAD

**Issue by swadey** [abeschneider/PEGParser#5]
Rules like:

```julia
sexpr = "(" + list(expr, white_space) + ")"
```
won't match `()` so that means rule writers have to write a separate rule like this:

```julia
sexpr0 = "(" ?(white_space) + ")"
```

to cover empty lists. I believe many PEG parser libraries have repsep and rep1sep to allow for minimum one and minimum zero lists.

**Comment by abeschneider** [comment]
Added a minimum value for list to allow for 0-length matches. There is an additional parameter for `list` that lets you set the minimum to 0 (it currently defaults to 1).

```
    @grammar grammar begin
      start = list(number, ",", 0)
      number = r"[0-9]"
    end

    (ast, pos, error) = parse(grammar, "", cache=false)
    @test error === nothing
    @test ast === nothing
```

**Comment by swadey** [comment]
wow, cool.  I'll try all of these things out over the weekend.
