### ISSUE TITLE
README contains a couple of errors

### ISSUE THREAD

**Issue by jonnydedwards** [abeschneider/PEGParser#6]
Hi,
thanks for package :)

first simple example in readme should read:

@grammar markup begin
  # this is the standard start rule
  start = bold_text

  # compose a sequence
  bold_text = bold_open + text + bold_close

  # use a regular expression to define the text
  text = r"[a-zA-Z]*"

  bold_open = '['
  bold_close = ']'
end

**Comment by abeschneider** [comment]
Fixed. Thanks!
