### ISSUE TITLE
Calc not working for me

### ISSUE THREAD

**Issue by jonnydedwards** [abeschneider/PEGParser#7]
Hi Again,
tried the calc.jl in examples

ERROR: `uncached_parse` has no method matching uncached_parse(::Grammar, ::EmptyRule, ::ASCIIString, ::Int64, ::Bool, ::Dict{String,Node})

Thanks again :)

**Comment by abeschneider** [comment]
Just to check, did you update your git repository and/or is there any chance you are using the wrong version of the library? That sounds like a bug I fixed a few commits ago.

**Comment by jonnydedwards** [comment]
Yes - I think that's the problem as I used the "pkg" command in julia - can I help you in anyway getting this version updated in julia package repo?
Jonny

**Comment by abeschneider** [comment]
I'm planning on updating Metadata in the next few days -- I want to exercise the code a bit more to make sure some of the design decisions made make sense.

If you want to play around with the git repo, you can uninstall the Metadata version via Pkg, and instead use the unstable github version.

Anyone interested in playing around with the unstable version will definitely help in speeding things up (i.e. find bugs and or weird behaviors).
